@baseUrl = http://localhost:3000
@token = {{ platformAdminLogin.response.body.access_token }}

### Login SYSTEM_ADMIN (necessário para acessar companies)
# @name platformAdminLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
     "login": "System Admin Claiver", 
    #   "login": "admin.empresA",
    #   "login": "hr.empresa",
    "password": "SystemAdmin@Senha"
}


### ========================================
### COMPANIES - SYSTEM_ADMIN
### ========================================

### Listar todas as empresas (com paginação)
GET {{baseUrl}}/companies
Authorization: Bearer {{token}}

### Listar todas as empresas
GET {{baseUrl}}/companies/all
Authorization: Bearer {{token}}

### Buscar empresa específica
GET {{baseUrl}}/companies/cmco084kk0000lt96pxlqot9s
Authorization: Bearer {{token}}

### Criar nova empresa
POST {{baseUrl}}/companies
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
    "name": "Empresa Exemplo", 
    "cnpj": "81.811.213/0001-03",
    "website": "https://www.empresa.com",
    "address": "Rua Exemplo, 123, São Paulo - SP",
    "country": "Brasil",
    "contactName": "Contato Exemplo",
    "contactEmail": "contato@empresa.com",
    "contactPhone": "(11) 99999-9299"
}

### Atualizar empresa
PATCH {{baseUrl}}/companies/cme61n51c0000lt62w7k6xkxf
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Empresa Exemplo", 
    "cnpj": "81.811.213/0001-03",
    "website": "https://www.empresa.com",
    "address": "Rua Exemplo, 123, São Paulo - SP",
    "country": "Brasil",
    "contactName": "Contato Exemplo",
    "contactEmail": "contato@empresa.com",
    "contactPhone": "(11) 99999-9299"
}

### Deletar empresa
DELETE {{baseUrl}}/companies/cme61n51c0000lt62w7k6xkxf
Authorization: Bearer {{token}}

### Restaurar empresa deletada
POST {{baseUrl}}/companies/cme61n51c0000lt62w7k6xkxf/restore
Authorization: Bearer {{token}}

### ========================================
### TESTES DE SEGURANÇA - COMPANIES
### ========================================

### ❌ TENTATIVA: ADMIN tentando acessar companies (deve falhar)
# @name adminLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "SystemAdmin123@Senha"
}

GET {{baseUrl}}/companies
Authorization: Bearer {{adminLogin.response.body.access_token}}

### ❌ TENTATIVA: HR tentando acessar companies (deve falhar)
# @name hrLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "hr@user.com",
    "password": "SystemAdmin123@Senha"
}

GET {{baseUrl}}/companies
Authorization: Bearer {{hrLogin.response.body.access_token}} 