@tokenAdmin = {{ adminLogin.response.body.access_token }}

### 
# @name adminLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "platformadmin@user.com",
    "password": "123456"
}

###
GET http://localhost:3000/users
Authorization: Bearer {{tokenAdmin}}

###
GET http://localhost:3000/users/cmco41oh1000altzzr6h8mr5m
Authorization: Bearer {{tokenAdmin}}

### Create Platform Admin
POST http://localhost:3000/users/platform-admin
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Platform Admin",
    "email": "platformadmin@user.com",
    "password": "123456",
    "role": "PLATFORM_ADMIN"
}

### Create Admin
POST http://localhost:3000/users/admin
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Admin",
    "email": "admin2@user.com",
    "password": "123456",
    "companyId": "<company_id>",
    "role": "ADMIN"
}

### Create Guard
POST http://localhost:3000/users/guard
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Guard",
    "email": "guard@user.com",
    "password": "123456",
    "companyId": "<company_id>",
    "unitIds": ["<unit_id1>", "<unit_id2>"],
    "role": "GUARD"
}

### Create HR
POST http://localhost:3000/users/hr
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "HR",
    "email": "hr@user.com",
    "password": "123456",
    "companyId": "<company_id>",
    "role": "HR"
}

### Create Resident
POST http://localhost:3000/users/resident
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Resident",
    "email": "resident@user.com",
    "password": "123456",
    "companyId": "<company_id>",
    "unitId": "<unit_id>",
    "role": "RESIDENT"
}
