@tokenAdmin = {{ adminLogin.response.body.access_token }}

### 
# @name adminLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "platformadmin@user.com",
    "password": "123456"
}

###
GET http://localhost:3000/users
Authorization: Bearer {{tokenAdmin}}


### Update Platform Admin (name and image)
PATCH http://localhost:3000/users/cmco084n70001lt96th7lafk8
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Platform Admin Updated",
    "profilePicture": "https://example.com/image1.png",
    "active": true
}

### Update Admin (name, image, active)
PATCH http://localhost:3000/users/<admin_id>
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Admin Updated",
    "profilePicture": "https://example.com/image2.png",
    "active": false
}

### Update Guard (name and image)
PATCH http://localhost:3000/users/<guard_id>
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Guard Updated",
    "profilePicture": "https://example.com/image3.png"
}

### Update HR (name, image, active)
PATCH http://localhost:3000/users/<hr_id>
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "HR Updated",
    "profilePicture": "https://example.com/image4.png",
    "active": true
}

### Update Resident (name and image)
PATCH http://localhost:3000/users/<resident_id>
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Resident Updated",
    "profilePicture": "https://example.com/image5.png"
} 